### PR TITLE
Add support for fence_aws

### PR DESCRIPTION
**Pull request by chhanz**
Hello @OndrejHome.
I hope doing well.

I added stonith device(`fence_aws`) so that this playbook can run on AWS.
And I tested it on Fedora, RHEL, CentOS, and Rocky Linux and there were no special problems.

If you don't mind, please check my PR.
Thanks.

### CODE REVIEW

**Comment by OndrejHome** [comment]
Hello @chhanz,

Thank you for using this role and for your time preparing this PR!

The changes are looking fairly simple, which is good, but I have some questions:
- [ ] 1. On which OS versions this PR was tested? From changes I would expect that it was tested on Fedora 32/33/34/35/36/37/38 and EL 7/8/9 (RHEL? CentOS? CentOS stream? Rocky?)
- [ ] 2. For fence_aws to work properly, do we require the IAM profile to be configured in AWS account?
- [ ] 3. As we need to specify `instance_id` in inventory, can we add the "sample inventory" for fence_aws into README.md?
- [ ] 4. Do we have any better public documentation for fence_aws configuration instead of links for https://access.redhat.com/articles/4175371 ? (that link points to huge SAP related document that happens to also have some fence_asw in it)
- [ ] 5. What is the reason for `fence_aws_options:` to be set to 'power_timeout=240 pcmk_reboot_timeout=600 pcmk_reboot_retries=4 pcmk_delay_max=45 op start timeout=600 op stop timeout=600 op monitor interval=180'? Those options are far from defaults, but what is the reason for that? I have heard somewhere that access to AWS API could be slow, but the values here are quite extreme. Does the fence_aws work using the default values only?
- [ ] 6. Do we need to install/configure `awscli` for fence_aws to work properly? (I'm asking as I don't have access to some testing AWS machines to confirm that.)

Also please let me know if any of questions is unclear. Thank you!

--
Ondrej (온드레이)

**Comment by chhanz** [comment]
> Hello @chhanz,
> 
> Thank you for using this role and for your time preparing this PR!
> 
> The changes are looking fairly simple, which is good, but I have some questions:
> 
>     * [ ]  1. On which OS versions this PR was tested? From changes I would expect that it was tested on Fedora 32/33/34/35/36/37/38 and EL 7/8/9 (RHEL? CentOS? CentOS stream? Rocky?)
> 
>     * [ ]  2. For fence_aws to work properly, do we require the IAM profile to be configured in AWS account?
> 
>     * [ ]  3. As we need to specify `instance_id` in inventory, can we add the "sample inventory" for fence_aws into README.md?
> 
>     * [ ]  4. Do we have any better public documentation for fence_aws configuration instead of links for https://access.redhat.com/articles/4175371 ? (that link points to huge SAP related document that happens to also have some fence_asw in it)
> 
>     * [ ]  5. What is the reason for `fence_aws_options:` to be set to 'power_timeout=240 pcmk_reboot_timeout=600 pcmk_reboot_retries=4 pcmk_delay_max=45 op start timeout=600 op stop timeout=600 op monitor interval=180'? Those options are far from defaults, but what is the reason for that? I have heard somewhere that access to AWS API could be slow, but the values here are quite extreme. Does the fence_aws work using the default values only?
> 
>     * [ ]  6. Do we need to install/configure `awscli` for fence_aws to work properly? (I'm asking as I don't have access to some testing AWS machines to confirm that.)
> 
> 
> Also please let me know if any of questions is unclear. Thank you!
> 
> -- Ondrej (온드레이)

Hello @OndrejHome .
The answer to your question is below.

Q1. On which OS versions this PR was tested? From changes I would expect that it was tested on Fedora 32/33/34/35/36/37/38 and EL 7/8/9 (RHEL? CentOS? CentOS stream? Rocky?)
    
A1. I tested on the versions listed below, and you can check the test log by referring to each gist.   
* Fedora 32 : [github gist](https://gist.github.com/chhanz/15afa5dc0ec30be0b954a33c5454960c)
* Fedora 33 : [github gist](https://gist.github.com/chhanz/4dd686bcf236e6c8ab526ef1024d0c04)
* Fedora 34 : [github gist](https://gist.github.com/chhanz/2663ce8f78699d1c0a9a31e9d386b0c8)
* Fedora 35 : [github gist](https://gist.github.com/chhanz/0ee0049f33084ea66f0e106b5de6ee28)
* Fedora 36 : [github gist](https://gist.github.com/chhanz/a69321d3f5f034c09179fe1d07b78f17)
* Fedora 37 : [github gist](https://gist.github.com/chhanz/9503ed21d68a8a00da29df087ec83b89)   
* Fedora 38 : [github gist](https://gist.github.com/chhanz/1647704b1bd49f280822c6c08ce1c1fa)   

* RHEL 7.9 : [github gist](https://gist.github.com/chhanz/01cc9d55e7606d66464e04e52c0b41dc)   
* RHEL 8.8 : [github gist](https://gist.github.com/chhanz/e36287b6d270e11d0c938858bb8d25f7)   
* RHEL 9.2 : [github gist](https://gist.github.com/chhanz/f958697495b8d32b087b67d8226870d9)   
* CentOS 7.9 : [github gist](https://gist.github.com/chhanz/82eca2485d1ae59628e98c663b58e473)   
* Rocky Linux 8.8 : [github gist](https://gist.github.com/chhanz/6d90caa5282059d560fa6d2c5028bd5c)   
* Rocky Linux 9.2 : [github gist](https://gist.github.com/chhanz/2c42826ef2de925718aaab0795e2d8aa)   

Q2. For fence_aws to work properly, do we require the IAM profile to be configured in AWS account?
   
A2. Yes, you must add an IAM profile by referring to the example below.   
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1424870324000",
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeInstances",
                "ec2:DescribeInstanceAttribute",
                "ec2:DescribeTags"
            ],
            "Resource": "*"
        },
        {
            "Sid": "Stmt1424870324001",
            "Effect": "Allow",
            "Action": [
                "ec2:ModifyInstanceAttribute",
                "ec2:RebootInstances",
                "ec2:StartInstances",
                "ec2:StopInstances"
            ],
            "Resource": [
                "arn:aws:ec2:<region>:<account-id>:instance/<instance-id-node1>",
                "arn:aws:ec2:<region>:<account-id>:instance/<instance-id-node2>"
            ]
        }
    ]
}
```
   
Q3. As we need to specify `instance_id` in inventory, can we add the "sample inventory" for fence_aws into README.md?
   
A3. Yes, I will add an example.   
```
$ cat inventory
[cluster]
172.31.0.1	instance_id="i-acbdefg1234567890"
172.31.0.2	instance_id="i-acbdefg0987654321"
```

Q4. Do we have any better public documentation for fence_aws configuration instead of links for https://access.redhat.com/articles/4175371 ? (that link points to huge SAP related document that happens to also have some fence_asw in it)
   
A4. I will change document to https://www.mankier.com/8/fence_aws.

Q5. What is the reason for `fence_aws_options:` to be set to 'power_timeout=240 pcmk_reboot_timeout=600 pcmk_reboot_retries=4 pcmk_delay_max=45 op start timeout=600 op stop timeout=600 op monitor interval=180'? Those options are far from defaults, but what is the reason for that? I have heard somewhere that access to AWS API could be slow, but the values here are quite extreme. Does the fence_aws work using the default values only?
   
A5. This option was added based on the document below.
There is no problem using the default value, but changes may be necessary for future operation.
   
https://docs.aws.amazon.com/sap/latest/sap-hana/sap-hana-on-aws-cluster-resources-1.html
https://access.redhat.com/articles/4175371#create-stonith

Please let me know if you would like to change this option to its default value.   

Q6. Do we need to install/configure `awscli` for fence_aws to work properly? (I'm asking as I don't have access to some testing AWS machines to confirm that.)
   
A6. AWS CLI is required if you are not using IAM profile [(Instance Profile)](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html).

Please tell me anything that needs to be changed or confirmed.
Thank you.

**Comment by OndrejHome** [comment]
Hello @chhanz,

Thank you for the update, great job on doing the testing and sorry for delay on my side.

As far as I can see only Fedora 32 cannot use the IAM profile while all other systems can. For that reason I think we can ignore the Fedora 32 here and focus only on systems that can use IAM profile. The `fence_aws_options` in my opinion should be empty, but we can provide the two links for SAP configurations that recommends changing them as example. As we will focus on supporting with this PR only IAM profile I would just not consider the `awscli` required. So below is final list of changes before merge of this PR:

- [ ] 1. (README.md, defaults/main.yml) make `fence_aws_options` default value of `''` and provide links to https://access.redhat.com/articles/4175371#create-stonith and https://docs.aws.amazon.com/sap/latest/sap-hana/sap-hana-on-aws-cluster-resources-1.html only as comment
- [ ] 2. (vars/fedora31.yml, vars/fedora32.yml) - remove support for fence_aws from these as they don't support use of IAM profile
- [ ] 3. (README.md) - (nitpick) move the `fence_aws_region: 'aws-region'` from `vars:` inside of role variables, example below:
   ~~~
   - hosts: cluster
      roles:
        - { role: 'ansible.ha-cluster-pacemaker', cluster_name: 'aws-cluster', cluster_configure_fence_xvm: false, cluster_configure_fence_aws: true, cluster_configure_stonith_style: 'one-device-per-cluster', enable_repos: false, fence_aws_region: 'aws-region' }
   ~~~
   
And enjoy the ongoing autumn harvest holidays :)

--
Ondrej (온드레이)

**Comment by chhanz** [comment]
Hello @OndrejHome .

I have updated the 3 items you requested. ([2241407](https://github.com/OndrejHome/ansible.ha-cluster-pacemaker/pull/32/commits/2241407107f516134fd91c6ad61fee0d222ab901))

Please tell me anything that needs to be changed or confirmed.
And enjoy the rest of your holidays, too! 
Thank you.

**Comment by OndrejHome** [comment]
Thank you @chhanz for changes!
Changes looks good to me, I have additionally pushed some small improvements for the documenting texts and also enabled the `fence_aws_options: ''` in defaults/main.yml to make sure that we don't fail on undefined variable.
The changes are now part of `master` branch and tagged as version `41.0.0`.

Once again thank you for your time and contribution!

--
Ondrej (온드레이)

**Pull request merged**
