### PR TITLE
Add new colocation influence

### PR DESCRIPTION
**Pull request by Obihoernchen**
https://clusterlabs.org/pacemaker/doc/2.1/Pacemaker_Explained/html/constraints.html#colocation-influence

Requires https://github.com/OndrejHome/ansible.pcs-modules-2/pull/41

### CODE REVIEW

**Comment by OndrejHome** [comment]
Hello @Obihoernchen ,

Thank you for opening this PR! 
As mentioned in the required PR from pcs-modules-2 I will merge this one once we are done with pcs-modules-2.

One small note: For completeness it would be nice to add the `influence: optional` also in here - https://github.com/OndrejHome/ansible.ha-cluster-pacemaker/blob/master/README.md?plain=1#L286-L291

Thank you!

**Comment by OndrejHome** [comment]
As the https://github.com/OndrejHome/ansible.pcs-modules-2/pull/41 is now merged I have also checked changes here and they work for me on Debian 11.7 (causing error if I try influence as expected) and on Fedora 38 where they configure it as expected.
Therefore let merge also this one in.

**Comment by OndrejHome** [comment]
Once again, thank you @Obihoernchen for contributions! 
The new influence option is available now in `master` branch or from tag `39.0.0` of this role.

**Comment by Obihoernchen** [comment]
@OndrejHome Thank you very much for your fast responses!

**Pull request merged**
