### PR TITLE
FIX Centos8 yum repos: Update mirror list in yum repos for Centos 8 d…

### PR DESCRIPTION
**Pull request by SpitchAG**
…istros

(fix Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist errors since Centos8 is EOL)

### CODE REVIEW

**Comment by OndrejHome** [comment]
Hello @SpitchAG,

Thank you  for another PR for this repository!
I understand the motivation for this, however in current form it is over reaching a bit too far - this code will change configuration not only for HA repository (which is intended for this role), but also BaseOS+Appstream repos (which could be possible managed differently) and any other repository in  `/etc/yum.repos.d/`.

- I'm OK with adjusting by default (`enable_repos: true`) the HA repository from `mirrorlist` to `baseurl` of vault.
- As the CentOS Linux (not stream) is EOL at minimum this role would need the BaseOS and AppStream repo to be functional
- I can imagine having new option `enable_c8vault_repos: true` to address this - by default it can be enabled and configure BaseOS and Appstream to use vault through `baseurl`.

If you agree with above, would it be possible to update the PR in following way?
- [ ] use `ini_file` module to remove `mirrorlist` and add `baseurl` for HA repository when `enable_repos | bool` (==true)
- [ ] use `ini_file` module to  remove `mirrorlist` and add `baseurl` for BaseOS and Appstream repositories when `enable_c8vault_repos| bool` on CentOS 8 Linux not stream
- [ ] add default value for `enable_c8vault_repos` into `defaults/main.yml` with some explanation that this is done due CentOS EOL

Please let me know if you have any questions or concerns to above. I will have time to look at this over coming weekend.

**Comment by SpitchAG** [comment]
Hi Ondre!
I totally agree, i missed the scope of this role indeed (being the first role failing in our playbook i did the change here without thinking too much),
i think we can (and probably should) perform this repositories trick outide of HA role and keep it clean.
You can close the PR, no problem; sorry for that
Regards

**Comment by OndrejHome** [comment]
Hi @SpitchAG ,

Thank you for the information. I have decided to at least include the HA repository configuration using the `ini_file` into role - now part of the `master` branch.

For enabling the AppStream and BaseOS repositories to use vault I have to first use playbook below that you can use for reference. I have tested it on CentOS 81, 8.2, 8.3, 8.4 and 8.5.

I will close this PR without merging, but thank you for bringing this up as it can be useful for the others!

~~~
---
- hosts: all
  tasks:
   - name: disable mirrorlist (8.1, 8.2)
     ini_file:
       dest: "{{ item.file }}"
       section: "{{ item.section }}"
       option: 'mirrorlist'
       create: 'no'
       mode: '0644'
       state: absent
     loop:
       - { file: '/etc/yum.repos.d/CentOS-Base.repo' , section: 'BaseOS' }
       - { file: '/etc/yum.repos.d/CentOS-AppStream.repo' , section: 'AppStream' }
     when: >-
       ansible_distribution_version in ['8.1', '8.2']
   - name: configure baseurl (8.1, 8.2)
     ini_file:
       dest: "{{ item.file }}"
       section: "{{ item.section }}"
       option: 'baseurl'
       value: 'http://vault.centos.org/$contentdir/$releasever/{{ item.section }}/$basearch/os/'
       create: 'no'
       mode: '0644'
       state: present
     loop:
       - { file: '/etc/yum.repos.d/CentOS-Base.repo' , section: 'BaseOS' }
       - { file: '/etc/yum.repos.d/CentOS-AppStream.repo' , section: 'AppStream' }
     when: >-
       ansible_distribution_version in ['8.1', '8.2']

   - name: disable mirrorlist (8.3, 8.4, 8.5)
     ini_file:
       dest: "{{ item.file }}"
       section: "{{ item.section }}"
       option: 'mirrorlist'
       create: 'no'
       mode: '0644'
       state: absent
     loop:
       - { file: '/etc/yum.repos.d/CentOS-Linux-BaseOS.repo' , section: 'BaseOS', url: 'BaseOS' }
       - { file: '/etc/yum.repos.d/CentOS-Linux-AppStream.repo' , section: 'AppStream', url: 'AppStream' }
     when: >-
       ansible_distribution_version in ['8.3', '8.4', '8.5']
   - name: configure baseurl (8.3, 8.4, 8.5)
     ini_file:
       dest: "{{ item.file }}"
       section: "{{ item.section }}"
       option: 'baseurl'
       value: 'http://vault.centos.org/$contentdir/$releasever/{{ item.url }}/$basearch/os/'
       create: 'no'
       mode: '0644'
       state: present
     loop:
       - { file: '/etc/yum.repos.d/CentOS-Linux-BaseOS.repo' , section: 'baseos', url: 'BaseOS' }
       - { file: '/etc/yum.repos.d/CentOS-Linux-AppStream.repo' , section: 'appstream', url: 'AppStream' }
     when: >-
       ansible_distribution_version in ['8.3', '8.4', '8.5']
~~~

**Comment by SpitchAG** [comment]
yes and indeed there is a concern about minor versions, seems that repo files are not named same, i ll fix it on my side,
thank you

**Pull request closed without merging**
