### PR TITLE
Simplify vars loading

### PR DESCRIPTION
**Pull request by tleguern**
Having one `include_vars` tasks and `with_first_found` allows for easier portability and long term maintenance.
It is possible to apply the same pattern to the `rhel_repos.yml`, `centos_repos.yml` and `debian10.yml` tasks files if you like it.

### CODE REVIEW

**Comment by OndrejHome** [comment]
Hello Tristan @tleguern ,

Nice idea! If you would have time to add also the `debian10.yaml` and the repos I will merge that here all together.
I have tested it briefly on few of my test clusters and changes works correctly (even with removed debian10.yaml - note that debian10.yaml include is duplicated twice in `main.yaml`, which seems to be my mistake when merging changes for debian earlier).

Please note that you have based this PR on top of Olipou repository instead of mine so I don't have write access to branch requested in this PR even with 'allow author changes to PR'.

**Comment by tleguern** [comment]
Oops, sorry about the wrong base repository. I will correct this during the week and also include the other change :)

Le 13 juin 2021 03:11:07 GMT+02:00, "Ondrej Faměra" ***@***.***> a écrit :
>Hello Tristan @tleguern ,
>
>Nice idea! If you would have time to add also the `debian10.yaml` and
>the repos I will merge that here all together.
>I have tested it briefly on few of my test clusters and changes works
>correctly (even with removed debian10.yaml - note that debian10.yaml
>include is duplicated twice in `main.yaml`, which seems to be my
>mistake when merging changes for debian earlier).
>
>Please note that you have based this PR on top of Olipou repository
>instead of mine so I don't have write access to branch requested in
>this PR even with 'allow author changes to PR'.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/OndrejHome/ansible.ha-cluster-pacemaker/pull/19#issuecomment-860133879

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tleguern** [comment]
Should be better now, I tested it on Debian.

**Comment by OndrejHome** [comment]
Thank you for fast response! I have checked it on CentOS 8 and Debian 10 and looks good to merge. On Ansible 2.8.18 I have received some deprecation warning (below) but because it is not present in Ansible 2.9 and it works well I think it is safe to ignore.
~~~
TASK [ondrejhome.ha-cluster-pacemaker : Include distribution specific tasks] ******************************************
task path: /root/pr19/roles/ondrejhome.ha-cluster-pacemaker/tasks/main.yml:26
[DEPRECATION WARNING]: Use errors="ignore" instead of skip. This feature will be removed in version 2.12. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Use errors="ignore" instead of skip. This feature will be removed in version 2.12. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
included: /root/pr19/roles/ondrejhome.ha-cluster-pacemaker/tasks/centos_repos.yml for 192.168.2.74, 192.168.2.75
~~~

**Comment by OndrejHome** [comment]
Thank you Tristan, @tleguern for another nice contribution!

**Comment by tleguern** [comment]
[Yes you can safely ignore this warning](https://github.com/ansible/ansible/pull/60161), it was “undeprecated” two years ago.

**Pull request merged**
